### ISSUE TITLE
Tip: Refactor

### ISSUE THREAD

**Issue by romullo-pereira** [VMarkz/mongure#1]
https://github.com/VMarkz/mongure/blob/ab36a8166eff115949c1fb53f773322ac1390f9f/src/core.clj#L25

Aqui esta sendo usado uma função let dentro de outra função let, sendo que a primeira não esta executando nada.
Não seria melhor deixar tudo em somente um let ?

Ex:
```
(let [starter (. MongodStarter getDefaultInstance)
      mongod-executable (reset! mongo-state (. starter prepare (prepare-mongo! port)))
      mongod (.start mongod-executable)
      mongo (MongoClient. addres port)
      db (. mongo getDB db-name)
      col (. db createCollection "testCol" (BasicDBObject.))]
  (. col save (BasicDBObject. "testDoc" (Date.))))
```

**Comment by VMarkz** [comment]
Legal, realmente vai ficar melhor, vou refatorar essa parte, inclusive, vou adicionar (try catch) caso alguma execução falhar.

**Comment by romullo-pereira** [comment]
Ai vai ficar show
